-- - 0 to disable vim implementation of filetype.
-- - 1 to disable both vim and neovim implementations.
--vim.g.did_load_filetypes = 0;
-- Enable additional filetype assignment from lua.
--vim.g.do_filetype_lua = 0;
